### PR TITLE
+ XMonad.Actions.Invert

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]
LGTM

**Comment by geekosaur** [comment]
Stack is complaining that the resolver has only dbus 1.2.15 but the build needs 1.2.21.

**Comment by l29ah** [comment]
Stack sux. Pushing relaxed deps.

**Review by psibi — COMMENTED** [review]
Sorry, somehow missed this PR. LGTM, Can you update the changelog and add `@since` haddock annotation for `0.17.1` ?

**Comment by l29ah** [comment]
Done.

**Comment by psibi** [comment]
@l29ah Seems there is some merge conflict with the CHANGELOG.md. Can you resolve it ?

**Comment by l29ah** [comment]
Done.

**Comment by psibi** [comment]
Thank you!

**Pull request merged**
